// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaBox.Storing;

namespace PizzaBox.Storing.Migrations
{
    [DbContext(typeof(PizzaBoxContext))]
    [Migration("20210512023738_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PizzaBox.Domain.Abstracts.AStore", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("EntityID");

                    b.ToTable("Stores");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AStore");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Cheese", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.ToTable("Cheeses");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Mozzerella",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Brie",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Cheddar",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "Feta",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "Swiss",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 6L,
                            Name = "No Cheese",
                            Price = 0.0m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Crust", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.ToTable("Crusts");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Original",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Thin",
                            Price = 1.0m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Gluten-Free",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "Pretzel",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "Deep Dish",
                            Price = 2.0m
                        },
                        new
                        {
                            EntityID = 6L,
                            Name = "Stuffed Crust",
                            Price = 3.0m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Customer", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("EntityID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Elizabeth Gainor"
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Darth Plagueis"
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Just Monika"
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "Calli Dream"
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "Kenneth Burtch"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("CustomerEntityID")
                        .HasColumnType("bigint");

                    b.Property<long?>("PizzaEntityID")
                        .HasColumnType("bigint");

                    b.Property<long?>("StoreEntityID")
                        .HasColumnType("bigint");

                    b.HasKey("EntityID");

                    b.HasIndex("CustomerEntityID");

                    b.HasIndex("PizzaEntityID");

                    b.HasIndex("StoreEntityID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            EntityID = 1L
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Pizza", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("CheeseEntityID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("CheeseEntityID2")
                        .HasColumnType("bigint");

                    b.Property<long?>("CrustEntityID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("CrustEntityID2")
                        .HasColumnType("bigint");

                    b.Property<long?>("SauceEntityID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("SauceEntityID2")
                        .HasColumnType("bigint");

                    b.Property<long?>("SizeEntityID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("SizeEntityID2")
                        .HasColumnType("bigint");

                    b.Property<long?>("ToppingEntityID1")
                        .HasColumnType("bigint");

                    b.HasKey("EntityID");

                    b.HasIndex("CheeseEntityID1");

                    b.HasIndex("CheeseEntityID2");

                    b.HasIndex("CrustEntityID1");

                    b.HasIndex("CrustEntityID2");

                    b.HasIndex("SauceEntityID1");

                    b.HasIndex("SauceEntityID2");

                    b.HasIndex("SizeEntityID1");

                    b.HasIndex("SizeEntityID2");

                    b.HasIndex("ToppingEntityID1");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Sauce", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.ToTable("Sauces");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Pizza Sauce - Classic",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Pizza Sauce - Exotic",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Buffalo",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "Garlic Ranch",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "Marinara",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 6L,
                            Name = "Pesto",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 7L,
                            Name = "Riggie Sauce",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 8L,
                            Name = "Sweet BBQ",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 9L,
                            Name = "Tangy BBQ",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 10L,
                            Name = "White Garlic",
                            Price = 0.0m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Size", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Small",
                            Price = 10.0m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Medium",
                            Price = 13.0m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Large",
                            Price = 15.0m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "XL",
                            Price = 20.0m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Topping", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("PizzaEntityID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.HasIndex("PizzaEntityID");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "American Bacon",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Anchovies",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Avocado",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "Banana Peppers",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "Basil",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 6L,
                            Name = "Bison",
                            Price = 2.50m
                        },
                        new
                        {
                            EntityID = 7L,
                            Name = "Black Olives",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 8L,
                            Name = "Breakfast Sausage",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 9L,
                            Name = "Broccoli",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 10L,
                            Name = "Buffalo Chicken",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 11L,
                            Name = "Buffalo Sauce",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 12L,
                            Name = "Canadian Bacon",
                            Price = 2.00m
                        },
                        new
                        {
                            EntityID = 13L,
                            Name = "Carmalized Onions",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 14L,
                            Name = "Chicken",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 15L,
                            Name = "Crab",
                            Price = 2.00m
                        },
                        new
                        {
                            EntityID = 16L,
                            Name = "Dill Pickles",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 17L,
                            Name = "Eggs",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 18L,
                            Name = "Elbows",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 19L,
                            Name = "Elk",
                            Price = 2.50m
                        },
                        new
                        {
                            EntityID = 20L,
                            Name = "Extra Cheese",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 21L,
                            Name = "Feta",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 22L,
                            Name = "Garlic",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 23L,
                            Name = "Green Peppers",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 24L,
                            Name = "Ground Beef",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 25L,
                            Name = "Ham",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 26L,
                            Name = "Italian Greens",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 27L,
                            Name = "Jalepeños",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 28L,
                            Name = "Lamb",
                            Price = 2.50m
                        },
                        new
                        {
                            EntityID = 29L,
                            Name = "Lobster",
                            Price = 3.00m
                        },
                        new
                        {
                            EntityID = 30L,
                            Name = "Meatball",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 31L,
                            Name = "Mushrooms",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 32L,
                            Name = "Pemeal Bacon",
                            Price = 2.00m
                        },
                        new
                        {
                            EntityID = 33L,
                            Name = "Pepperoni",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 34L,
                            Name = "Pesto",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 35L,
                            Name = "Pineapple",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 36L,
                            Name = "Prosciutto",
                            Price = 2.00m
                        },
                        new
                        {
                            EntityID = 37L,
                            Name = "Pulled Pork",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 38L,
                            Name = "Ranch",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 39L,
                            Name = "Red Onion",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 40L,
                            Name = "Riggie Sauce",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 41L,
                            Name = "Salami",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 42L,
                            Name = "Sausage",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 43L,
                            Name = "Scallions",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 44L,
                            Name = "Scallops",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 45L,
                            Name = "Shaved Beef",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 46L,
                            Name = "Shrimp",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 47L,
                            Name = "Spinach",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 48L,
                            Name = "Sun Dried Tomatoes",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 49L,
                            Name = "Sweet BBQ Sauce",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 50L,
                            Name = "Tangy BBQ Sauce",
                            Price = 0.50m
                        },
                        new
                        {
                            EntityID = 51L,
                            Name = "Tomatoes",
                            Price = 1.00m
                        },
                        new
                        {
                            EntityID = 52L,
                            Name = "Venison",
                            Price = 3.00m
                        },
                        new
                        {
                            EntityID = 53L,
                            Name = "Yellow Onion",
                            Price = 1.00m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.ChicagoStore", b =>
                {
                    b.HasBaseType("PizzaBox.Domain.Abstracts.AStore");

                    b.HasDiscriminator().HasValue("ChicagoStore");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Main St."
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "West Rd."
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "North Ave."
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "East St."
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "South Cir."
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.NewYorkStore", b =>
                {
                    b.HasBaseType("PizzaBox.Domain.Abstracts.AStore");

                    b.HasDiscriminator().HasValue("NewYorkStore");

                    b.HasData(
                        new
                        {
                            EntityID = 6L,
                            Name = "South James St."
                        },
                        new
                        {
                            EntityID = 7L,
                            Name = "Erie Blvd."
                        },
                        new
                        {
                            EntityID = 8L,
                            Name = "Black River Blvd."
                        },
                        new
                        {
                            EntityID = 9L,
                            Name = "Name_Pending Rd."
                        },
                        new
                        {
                            EntityID = 10L,
                            Name = "Artist Ln."
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerEntityID");

                    b.HasOne("PizzaBox.Domain.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaEntityID");

                    b.HasOne("PizzaBox.Domain.Abstracts.AStore", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreEntityID");

                    b.Navigation("Customer");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Pizza", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Cheese", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("CheeseEntityID1");

                    b.HasOne("PizzaBox.Domain.Models.Cheese", null)
                        .WithMany()
                        .HasForeignKey("CheeseEntityID2");

                    b.HasOne("PizzaBox.Domain.Models.Crust", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("CrustEntityID1");

                    b.HasOne("PizzaBox.Domain.Models.Crust", null)
                        .WithMany()
                        .HasForeignKey("CrustEntityID2");

                    b.HasOne("PizzaBox.Domain.Models.Sauce", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("SauceEntityID1");

                    b.HasOne("PizzaBox.Domain.Models.Sauce", null)
                        .WithMany()
                        .HasForeignKey("SauceEntityID2");

                    b.HasOne("PizzaBox.Domain.Models.Size", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("SizeEntityID1");

                    b.HasOne("PizzaBox.Domain.Models.Size", null)
                        .WithMany()
                        .HasForeignKey("SizeEntityID2");

                    b.HasOne("PizzaBox.Domain.Models.Topping", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("ToppingEntityID1");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Topping", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaEntityID");
                });

            modelBuilder.Entity("PizzaBox.Domain.Abstracts.AStore", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Cheese", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Crust", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Sauce", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Size", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Topping", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
