// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaBox.Storing;

namespace PizzaBox.Storing.Migrations
{
    [DbContext(typeof(PizzaBoxContext))]
    [Migration("20210506191116_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PizzaBox.Domain.Models.Crust", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.ToTable("Crusts");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Original",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Thin",
                            Price = 1.0m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Gluten-Free",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "Pretzel",
                            Price = 1.50m
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "Stuffed Crust",
                            Price = 3.0m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Size", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Small",
                            Price = 10.0m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Medium",
                            Price = 13.0m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Large",
                            Price = 15.0m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "XL",
                            Price = 20.0m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Topping", b =>
                {
                    b.Property<long>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EntityID");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            EntityID = 1L,
                            Name = "Cheese",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 2L,
                            Name = "Marinara",
                            Price = 0.0m
                        },
                        new
                        {
                            EntityID = 3L,
                            Name = "Pepperoni",
                            Price = 1.0m
                        },
                        new
                        {
                            EntityID = 4L,
                            Name = "Ham",
                            Price = 1.5m
                        },
                        new
                        {
                            EntityID = 5L,
                            Name = "Hawaiian",
                            Price = 1.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
